### ISSUE TITLE
Generating Javascript code

### ISSUE THREAD

**Issue by soywiz** [justjohn/twig.js#2]
It would be great if the Template.render were a plain Javascript function. At this moment if I'm not wrong it just interprets a set of nodes instead of creating a native javascript function with "eval".

Because of the overhead of that interpretation, it is a bit slow for me.

Here is a project that generates javascript code (thought it is generated by PHP):
https://github.com/schmittjoh/twig.js

But the idea is similar: the engine loads the template, compiles it into plain Javascript and then returns a javascript native function that can be executed directly.

I have done something similar for .NET: https://github.com/soywiz/csharputils/tree/master/CSharpUtils/CSharpUtils.Templates/Templates
https://github.com/soywiz/csharputils/blob/master/CSharpUtils/CSharpUtilsTests/Templates/TemplateTest.cs

If you want I can help you implementing the javascript dynarec for twig.js.

**Comment by evgenius** [comment]
This library https://github.com/schmittjoh/twig.js will probably never add support for the function "template_from_string" because of the way it works. Once the template is compiled to JS, there's no way to compile something extra.
So that's the difference between these two libraries. Every user can choose depending on their needs. In FoxyCart we decided John's way would work better for us.
